import solarPanelImg from "@/assets/industrial-solar.png";
import solarInverterImg from "@/assets/hybrid-inverter.png";
import solarBatteryImg from "@/assets/battery-storage.png";
import solarChargeControllerImg from "@/assets/industrial-solar-clear.png";
import solarStreetLightImg from "@/assets/green-city-solar.png";
import solarWaterPumpImg from "@/assets/industrial-solar-facility.png";

export interface ProductDetail {
  id: string;
  title: string;
  overview: string;
  features: string[];
  specs: Record<string, string>;
  applications: string[];
  benefits: string[];
  image: string;
}

export const productsData: Record<string, ProductDetail> = {
  "solar-panel": {
    id: "solar-panel",
    image: solarPanelImg,
    title: "High-Efficiency Solar Panels",
    overview: "Solar panels are the heart of any renewable energy system, acting as the primary energy harvester. Our high-efficiency Monocrystalline PERC (Passivated Emitter and Rear Cell) panels utilize advanced photovoltaic technology to convert sunlight directly into DC electricity.",
    features: [
      "MBB (Multi-Busbar) Technology: Reduces internal resistance.",
      "Higher Power Density: Generates more power per square foot.",
      "Anti-PID Design: Protection against Potential Induced Degradation.",
      "High Durability: Reinforced frames and tempered glass."
    ],
    specs: {
      "Module Type": "Monocrystalline PERC",
      "Rated Power (Pmax)": "450W - 550W",
      "Module Efficiency": "20.9% - 21.5%",
      "Open Circuit Voltage (Voc)": "49.5V - 50.2V",
      "Short Circuit Current (Isc)": "11.5A - 13.8A",
      "Max System Voltage": "1000V / 1500V DC",
      "Operating Temperature": "-40°C to +85°C",
      "Warranty": "25-Year Linear Performance Warranty"
    },
    applications: [
      "Residential Rooftop Installations",
      "Commercial & Industrial (C&I) Solar Farms",
      "Solar-powered Irrigation Systems",
      "Off-grid Power Stations"
    ],
    benefits: [
      "Significant Savings on electricity bills.",
      "Eco-Friendly: Zero carbon emissions.",
      "Long-Term Reliability: Designed to last 25+ years."
    ]
  },
  "solar-inverter": {
    id: "solar-inverter",
    image: solarInverterImg,
    title: "Advanced Solar Inverters",
    overview: "Solar Inverters perform the critical task of converting the Direct Current (DC) electricity generated by solar panels into stable, usable Alternating Current (AC) for your home or business appliances.",
    features: [
      "Dual MPPT Tracking: Optimizes power harvesting.",
      "Pure Sine Wave Output: Ensures safety for sensitive electronics.",
      "Smart Monitoring: Integrated Wi-Fi/4G for real-time tracking.",
      "Quick Switch-over: Provides seamless power backup."
    ],
    specs: {
      "Inverter Type": "Hybrid / On-Grid String",
      "Rated AC Output Power": "3kW / 5kW / 10kW",
      "Max. Efficiency": "≥98.2%",
      "MPPT Voltage Range": "120V - 550V DC",
      "Output Voltage / Freq": "230V AC ± 1%, 50/60Hz",
      "Total Harmonic Distortion": "< 3% (Linear Load)",
      "Cooling Method": "Natural Convection / Smart Fan",
      "IP Rating": "IP65 (Outdoor Rated)"
    },
    applications: [
      "Grid-Interactive Residential Systems",
      "Self-Consumption Optimization",
      "Commercial Energy Management"
    ],
    benefits: [
      "Maximum Yield with high conversion efficiency.",
      "Grid Stability: Helps manage peak loads.",
      "User Control: Monitor savings via mobile app."
    ]
  },
  "solar-battery": {
    id: "solar-battery",
    image: solarBatteryImg,
    title: "Solar Lithium Battery (ESS)",
    overview: "Our Lithium Iron Phosphate (LiFePO4) solar batteries provide a safe, high-density energy storage solution, allowing you to use solar power even after the sun goes down.",
    features: [
      "LiFePO4 Chemistry: Safest lithium technology.",
      "Intelligent BMS: Built-in protection system.",
      "Modular Design: Easily stackable capacity.",
      "High Cycle Life: Rated for over 6,000 cycles."
    ],
    specs: {
      "Battery Chemistry": "Lithium Iron Phosphate (LiFePO4)",
      "Nominal Capacity": "5.12 kWh / 10.24 kWh",
      "Nominal Voltage": "48V / 51.2V",
      "Depth of Discharge (DoD)": "90%",
      "Cycle Life": "> 6,000 cycles @ 25°C",
      "Communication": "RS485 / CAN",
      "Charging Temp Range": "0°C to 50°C"
    },
    applications: [
      "Home Energy Storage Systems (ESS)",
      "Backup Power for Critical Infrastructure",
      "Off-Grid Cabin & Tiny Home Power"
    ],
    benefits: [
      "Energy Independence: Power your home 24/7.",
      "Safety First: Non-toxic materials.",
      "Compact Footprint: Space-saving design."
    ]
  },
  "solar-charge-controller": {
    id: "solar-charge-controller",
    image: solarChargeControllerImg,
    title: "MPPT Solar Charge Controller",
    overview: "Our MPPT controllers use an advanced algorithm to track the panels' peak power point, increasing charging efficiency by up to 30% compared to traditional PWM controllers.",
    features: [
      "Ultra-Fast MPPT Tracking: Adapts to weather changes.",
      "Multiple Load Modes: Manual, Dusk-to-Dawn, and Timer.",
      "Battery Compatibility: Supports Lead-Acid and Lithium.",
      "LCD Display: Real-time system monitoring."
    ],
    specs: {
      "Controller Type": "MPPT (Max Power Point Tracking)",
      "Max. Charge Current": "40A / 60A / 80A",
      "System Voltage": "12V / 24V / 36V / 48V (Auto)",
      "Max. PV Input Voltage": "150V DC (Voc)",
      "Tracking Efficiency": "> 99.5%",
      "Conversion Efficiency": "Up to 98%",
      "Protection": "Short-circuit, Reverse Polarity"
    },
    applications: [
      "Off-Grid Solar Kits",
      "RV and Marine Solar Systems",
      "Solar Street Light Control"
    ],
    benefits: [
      "Optimized Charging for maximum power extraction.",
      "Extended Battery Life with smart regulation.",
      "Cost-Effective performance enhancement."
    ]
  },
  "solar-street-light": {
    id: "solar-street-light",
    image: solarStreetLightImg,
    title: "All-in-One Solar Street Lights",
    overview: "Our All-in-One Solar Street Lights combine a solar panel, LED light source, LiFePO4 battery, and an intelligent motion sensor into a single, compact unit.",
    features: [
      "PIR Motion Sensor: Conserves energy when no motion.",
      "High-Lumen LEDs: Bright and uniform lighting.",
      "No-Wiring Installation: Mount on pole or wall.",
      "Weatherproof: IP65 rated durable design."
    ],
    specs: {
      "LED Power": "30W / 60W / 100W",
      "Luminous Flux": "140 - 160 Lm/W",
      "Battery Type": "LiFePO4 (Integrated)",
      "Working Time": "12 Hours (3-5 Day Backup)",
      "Mounting Height": "4m - 8m",
      "Color Temperature": "6000K (Cool White)",
      "Sensor Type": "PIR / Microwave Sensor"
    },
    applications: [
      "Campus & Residential Area Lighting",
      "Public Parks & Walkways",
      "Industrial Facility Perimeters",
      "Remote Village Lighting"
    ],
    benefits: [
      "Zero Running Cost: Powered by free sun energy.",
      "Enhanced Safety and Security.",
      "Eco-Friendly and maintenance-free."
    ]
  },
  "solar-water-pump": {
    id: "solar-water-pump",
    image: solarWaterPumpImg,
    title: "Solar Water Pump Systems",
    overview: "Designed for agriculture and remote water supply, our Solar Water Pump systems use sun power to lift water from deep wells, rivers, or lakes.",
    features: [
      "Brushless DC Motor: High efficiency and long life.",
      "MPPT Controller: Frequency control for motor speed.",
      "Dry-Run Protection: Automatic shut off.",
      "Stainless Steel: AISI 304/316 corrosion resistance."
    ],
    specs: {
      "Pump Type": "Submersible / Surface Pump",
      "Power Range": "0.5 HP - 10 HP",
      "Max. Head (Lift)": "Up to 150 Meters",
      "Max. Flow Rate": "Up to 20,000 L/H",
      "Input Voltage": "24V - 550V DC",
      "Controller Tech": "MPPT with VFD Control",
      "Outlet Size": "1.25 inch / 2 inch / 3 inch"
    },
    applications: [
      "Agricultural Irrigation",
      "Livestock Watering",
      "Community Drinking Water Supply",
      "Drip Irrigation & Greenhouses"
    ],
    benefits: [
      "Independent Irrigation without diesel costs.",
      "Low Maintenance in rugged environments.",
      "Automatic Speed Adjustment based on sun."
    ]
  }
};
