import solarPanelImg from "@/assets/high-efficiency-solar-panels.jpg";
import solarInverterImg from "@/assets/hybrid-inverter.png";
import solarBatteryImg from "@/assets/battery-storage.png";
import solarChargeControllerImg from "@/assets/service-installation.png";
import solarStreetLightImg from "@/assets/green-city-solar.png";
import solarWaterPumpImg from "@/assets/industrial-solar-facility.png";
import solarSolutionImg from "@/assets/project-new.png";
import solarMonitoringImg from "@/assets/solar-monitoring.png";
import portableSolarImg from "@/assets/portable-solar.png";

export interface ProductType {
  name: string;
  description: string;
}

export interface ProductDetail {
  id: string;
  title: string;
  overview: string;
  features: string[];
  specs: Record<string, string>;
  applications: string[];
  benefits: string[];
  image: string;
  lifespan: string;
  warranty: string;
  types: ProductType[];
}

export const productsData: Record<string, ProductDetail> = {
  "solar-panel": {
    id: "solar-panel",
    image: solarPanelImg,
    title: "High-Efficiency Solar Panels",
    overview: "Solar panels are the heart of any renewable energy system, acting as the primary energy harvester. Our high-efficiency Monocrystalline PERC (Passivated Emitter and Rear Cell) panels utilize advanced photovoltaic technology to convert sunlight directly into DC electricity.",
    features: [
      "MBB (Multi-Busbar) Technology: Reduces internal resistance.",
      "Higher Power Density: Generates more power per square foot.",
      "Anti-PID Design: Protection against Potential Induced Degradation.",
      "High Durability: Reinforced frames and tempered glass."
    ],
    specs: {
      "Module Type": "Monocrystalline PERC",
      "Rated Power (Pmax)": "450W - 550W",
      "Module Efficiency": "20.9% - 21.5%",
      "Open Circuit Voltage (Voc)": "49.5V - 50.2V",
      "Short Circuit Current (Isc)": "11.5A - 13.8A",
      "Max System Voltage": "1000V / 1500V DC",
      "Operating Temperature": "-40°C to +85°C",
      "Warranty": "25-Year Linear Performance Warranty"
    },
    applications: [
      "Residential Rooftop Installations",
      "Commercial & Industrial (C&I) Solar Farms",
      "Solar-powered Irrigation Systems",
      "Off-grid Power Stations"
    ],
    benefits: [
      "Significant Savings on electricity bills.",
      "Eco-Friendly: Zero carbon emissions.",
      "Long-Term Reliability: Designed to last 25+ years."
    ],
    lifespan: "25–30 Years",
    warranty: "25-Year Linear Performance Warranty",
    types: [
      { name: "Monocrystalline PERC", description: "Highest efficiency (20-22%) and sleek black aesthetics. Best for limited roof space." },
      { name: "Polycrystalline", description: "Cost-effective blue-tinted panels. Great for large open spaces where space isn't a premium." },
      { name: "Bifacial Panels", description: "Captures sunlight from both front and back, boosting yield by up to 30% on reflective surfaces." },
      { name: "Thin-Film Solar", description: "Lightweight and flexible, ideal for curved surfaces or portable applications." }
    ]
  },
  "solar-inverter": {
    id: "solar-inverter",
    image: solarInverterImg,
    title: "Advanced Solar Inverters",
    overview: "Solar Inverters perform the critical task of converting the Direct Current (DC) electricity generated by solar panels into stable, usable Alternating Current (AC) for your home or business appliances.",
    features: [
      "Dual MPPT Tracking: Optimizes power harvesting.",
      "Pure Sine Wave Output: Ensures safety for sensitive electronics.",
      "Smart Monitoring: Integrated Wi-Fi/4G for real-time tracking.",
      "Quick Switch-over: Provides seamless power backup."
    ],
    specs: {
      "Inverter Type": "Hybrid / On-Grid String",
      "Rated AC Output Power": "3kW / 5kW / 10kW",
      "Max. Efficiency": "≥98.2%",
      "MPPT Voltage Range": "120V - 550V DC",
      "Output Voltage / Freq": "230V AC ± 1%, 50/60Hz",
      "Total Harmonic Distortion": "< 3% (Linear Load)",
      "Cooling Method": "Natural Convection / Smart Fan",
      "IP Rating": "IP65 (Outdoor Rated)"
    },
    applications: [
      "Grid-Interactive Residential Systems",
      "Self-Consumption Optimization",
      "Commercial Energy Management"
    ],
    benefits: [
      "Maximum Yield with high conversion efficiency.",
      "Grid Stability: Helps manage peak loads.",
      "User Control: Monitor savings via mobile app."
    ],
    lifespan: "10–15 Years",
    warranty: "5–10 Years (Extendable)",
    types: [
      { name: "On-Grid (String) Inverters", description: "Most common type. Connects directly to the grid to reduce electricity bills." },
      { name: "Hybrid Inverters", description: "The smartest choice. Manages both solar panels and battery storage for backup power." },
      { name: "Off-Grid Inverters", description: "Designed for remote areas. Works entirely split from the utility grid." },
      { name: "Microinverters", description: "Installed on each panel. Maximizes output if part of the roof is shadowed." }
    ]
  },
  "solar-battery": {
    id: "solar-battery",
    image: solarBatteryImg,
    title: "Solar Lithium Battery (ESS)",
    overview: "Our Lithium Iron Phosphate (LiFePO4) solar batteries provide a safe, high-density energy storage solution, allowing you to use solar power even after the sun goes down.",
    features: [
      "LiFePO4 Chemistry: Safest lithium technology.",
      "Intelligent BMS: Built-in protection system.",
      "Modular Design: Easily stackable capacity.",
      "High Cycle Life: Rated for over 6,000 cycles."
    ],
    specs: {
      "Battery Chemistry": "Lithium Iron Phosphate (LiFePO4)",
      "Nominal Capacity": "5.12 kWh / 10.24 kWh",
      "Nominal Voltage": "48V / 51.2V",
      "Depth of Discharge (DoD)": "90%",
      "Cycle Life": "> 6,000 cycles @ 25°C",
      "Communication": "RS485 / CAN",
      "Charging Temp Range": "0°C to 50°C"
    },
    applications: [
      "Home Energy Storage Systems (ESS)",
      "Backup Power for Critical Infrastructure",
      "Off-Grid Cabin & Tiny Home Power"
    ],
    benefits: [
      "Energy Independence: Power your home 24/7.",
      "Safety First: Non-toxic materials.",
      "Compact Footprint: Space-saving design."
    ],
    lifespan: "10–12 Years (6000+ Cycles)",
    warranty: "5–10 Years Performance Warranty",
    types: [
      { name: "LiFePO4 (LFP)", description: "The safest lithium chemistry. Non-toxic, fire-resistant, and supports deep discharge." },
      { name: "Lead-Acid (GEL/AGM)", description: "Lower upfront cost but shorter lifespan. Used in basic off-grid setups." },
      { name: "Wall-Mounted ESS", description: "Space-saving design that mounts on your wall like a modern appliance." },
      { name: "Stackable Modules", description: "Expandable storage. Add more battery packs as your energy needs grow." }
    ]
  },
  "solar-charge-controller": {
    id: "solar-charge-controller",
    image: solarChargeControllerImg,
    title: "MPPT Solar Charge Controller",
    overview: "Our MPPT controllers use an advanced algorithm to track the panels' peak power point, increasing charging efficiency by up to 30% compared to traditional PWM controllers.",
    features: [
      "Ultra-Fast MPPT Tracking: Adapts to weather changes.",
      "Multiple Load Modes: Manual, Dusk-to-Dawn, and Timer.",
      "Battery Compatibility: Supports Lead-Acid and Lithium.",
      "LCD Display: Real-time system monitoring."
    ],
    specs: {
      "Controller Type": "MPPT (Max Power Point Tracking)",
      "Max. Charge Current": "40A / 60A / 80A",
      "System Voltage": "12V / 24V / 36V / 48V (Auto)",
      "Max. PV Input Voltage": "150V DC (Voc)",
      "Tracking Efficiency": "> 99.5%",
      "Conversion Efficiency": "Up to 98%",
      "Protection": "Short-circuit, Reverse Polarity"
    },
    applications: [
      "Off-Grid Solar Kits",
      "RV and Marine Solar Systems",
      "Solar Street Light Control"
    ],
    benefits: [
      "Optimized Charging for maximum power extraction.",
      "Extended Battery Life with smart regulation.",
      "Cost-Effective performance enhancement."
    ],
    lifespan: "8–10 Years",
    warranty: "2–5 Years",
    types: [
      { name: "MPPT Controllers", description: "Maximum Power Point Tracking. Extracts up to 30% more power than PWM." },
      { name: "PWM Controllers", description: "Pulse Width Modulation. Simple and economical for small 12V systems." },
      { name: "Waterproof Controllers", description: "IP68 rated for marine, RV, and outdoor lighting applications." }
    ]
  },
  "solar-street-light": {
    id: "solar-street-light",
    image: solarStreetLightImg,
    title: "All-in-One Solar Street Lights",
    overview: "Our All-in-One Solar Street Lights combine a solar panel, LED light source, LiFePO4 battery, and an intelligent motion sensor into a single, compact unit.",
    features: [
      "PIR Motion Sensor: Conserves energy when no motion.",
      "High-Lumen LEDs: Bright and uniform lighting.",
      "No-Wiring Installation: Mount on pole or wall.",
      "Weatherproof: IP65 rated durable design."
    ],
    specs: {
      "LED Power": "30W / 60W / 100W",
      "Luminous Flux": "140 - 160 Lm/W",
      "Battery Type": "LiFePO4 (Integrated)",
      "Working Time": "12 Hours (3-5 Day Backup)",
      "Mounting Height": "4m - 8m",
      "Color Temperature": "6000K (Cool White)",
      "Sensor Type": "PIR / Microwave Sensor"
    },
    applications: [
      "Campus & Residential Area Lighting",
      "Public Parks & Walkways",
      "Industrial Facility Perimeters",
      "Remote Village Lighting"
    ],
    benefits: [
      "Zero Running Cost: Powered by free sun energy.",
      "Enhanced Safety and Security.",
      "Eco-Friendly and maintenance-free."
    ],
    lifespan: "5–8 Years (LED & Battery)",
    warranty: "2–3 Years All-Inclusive",
    types: [
      { name: "All-in-One Integrated", description: "Panel, battery, and light in one housing. Easiest theft-proof installation." },
      { name: "Split-Type Solar Lights", description: "Adjustable panel orientation to maximize sun exposure in shaded areas." },
      { name: "Flood Lights with Motion", description: "High intensity lighting that activates when motion is detected." }
    ]
  },
  "solar-water-pump": {
    id: "solar-water-pump",
    image: solarWaterPumpImg,
    title: "Solar Water Pump Systems",
    overview: "Designed for agriculture and remote water supply, our Solar Water Pump systems use sun power to lift water from deep wells, rivers, or lakes.",
    features: [
      "Brushless DC Motor: High efficiency and long life.",
      "MPPT Controller: Frequency control for motor speed.",
      "Dry-Run Protection: Automatic shut off.",
      "Stainless Steel: AISI 304/316 corrosion resistance."
    ],
    specs: {
      "Pump Type": "Submersible / Surface Pump",
      "Power Range": "0.5 HP - 10 HP",
      "Max. Head (Lift)": "Up to 150 Meters",
      "Max. Flow Rate": "Up to 20,000 L/H",
      "Input Voltage": "24V - 550V DC",
      "Controller Tech": "MPPT with VFD Control",
      "Outlet Size": "1.25 inch / 2 inch / 3 inch"
    },
    applications: [
      "Agricultural Irrigation",
      "Livestock Watering",
      "Community Drinking Water Supply",
      "Drip Irrigation & Greenhouses"
    ],
    benefits: [
      "Independent Irrigation without diesel costs.",
      "Low Maintenance in rugged environments.",
      "Automatic Speed Adjustment based on sun."
    ],
    lifespan: "15–20 Years (Pump Body)",
    warranty: "1–2 Years on Electronics; 5 Years on Pump",
    types: [
      { name: "Submersible Pumps", description: "Installed deep inside borewells. Ideal for high-head water lifting." },
      { name: "Surface Pumps", description: "Placed on the ground near rivers or ponds. High flow rate for irrigation." },
      { name: "DC Brushless Pumps", description: "Operates directly from solar panels without needing an inverter." }
    ]
  },
  "solar-energy-solutions": {
    id: "solar-energy-solutions",
    image: solarSolutionImg,
    title: "Solar Energy Solutions",
    overview: "Comprehensive solar systems for clean, reliable, and cost-effective power generation across industrial, commercial, and infrastructure projects. We provide end-to-end integration of panels, inverters, and storage.",
    features: [
      "Turnkey Integration: Complete system setup.",
      "Scalable Architecture: Grows with your needs.",
      "High-Efficiency Output: Maximum ROI.",
      "Grid-Tie & Off-Grid Options: Flexible deployment."
    ],
    specs: {
      "System Type": "Grid-Interactive / Off-Grid",
      "Capacity Range": "10kW to 1MW+",
      "Panel Technology": "Mono-PERC / Bifacial",
      "Mounting System": "Roof / Ground / Carport",
      "Inverter Tech": "String / Central Inverters"
    },
    applications: [
      "Industrial Factories",
      "Commercial Offices",
      "Agricultural Farms",
      "Residential Complexes"
    ],
    benefits: [
      "Reduced Operational Costs.",
      "Corporate Sustainability Compliance.",
      "Protection against rising energy tariffs."
    ],
    lifespan: "25+ Years",
    warranty: "System-wide 5-Year Maintenance; 25-Year Panel Warranty",
    types: [
      { name: "Residential Rooftop", description: "Tailored for homes to achieve zero-cost electricity bills." },
      { name: "Commercial & Industrial", description: "Large scale setups for factories to reduce operational overheads." },
      { name: "Ground-Mount Farms", description: "Utility-scale installations on open land for power generation." }
    ]
  },
  "smart-solar-monitoring": {
    id: "smart-solar-monitoring",
    image: solarMonitoringImg,
    title: "Smart Solar Monitoring",
    overview: "Cloud-based monitoring systems that give you full visibility into your energy production and savings in real-time. Analyze performance metrics and detect issues before they affect your yield.",
    features: [
      "Real-time Analytics: Instant data visualization.",
      "Fault Alerts: Automatic notifications for issues.",
      "Cloud Accessibility: Access from anywhere.",
      "Historical Reports: Track savings over time."
    ],
    specs: {
      "Platform": "Web & Mobile App (iOS/Android)",
      "Connectivity": "Wi-Fi / LAN / 4G LTE",
      "Data Interval": "1 - 5 Minutes",
      "Protocol Support": "Modbus RTU / TCP",
      "Security": "End-to-End Encryption"
    },
    applications: [
      "Remote Site Management",
      "Commercial Energy Auditing",
      "Residential Performance Tracking"
    ],
    benefits: [
      "Peace of Mind: Know your system is working.",
      "Optimized Maintenance: Data-driven servicing.",
      "Maximized Yield: Identify and fix underperformance."
    ],
    lifespan: "Continuous Software Updates",
    warranty: "2-Year Hardware Warranty; Lifetime Software Access",
    types: [
      { name: "Real-time Dashboards", description: "Live visualization of current production vs home consumption." },
      { name: "Predictive Maintenance", description: "AI alerts you before a panel or inverter fails." },
      { name: "Remote Shutdown", description: "Safety feature to remotely isolate the system during emergencies." }
    ]
  },
  "portable-solar-kits": {
    id: "portable-solar-kits",
    image: portableSolarImg,
    title: "Portable Solar Kits",
    overview: "Reliable solar power on the go. Perfectly designed for remote sites, camping, and emergency backup power needs. Compact, lightweight, and easy to deploy.",
    features: [
      "Foldable Design: Easy to carry and store.",
      "Plug-and-Play: No complex installation required.",
      "Multiple Outputs: USB-C, DC, and AC support.",
      "Weather Resistant: IP65 Rated for outdoor use."
    ],
    specs: {
      "Panel Type": "Foldable Monocrystalline",
      "Power Output": "100W / 200W / 400W",
      "Battery Capacity": "Integrated 500Wh - 2000Wh",
      "Charge Time": "4-8 Hours (Sun-dependent)",
      "Total Weight": "5kg to 15kg"
    },
    applications: [
      "Off-road Camping & Overlanding",
      "Emergency Disaster Relief",
      "Remote Field Stations",
      "Mobile Device Charging"
    ],
    benefits: [
      "Go Anywhere: True energy freedom.",
      "Quiet Operation: No noise like gasoline generators.",
      "Low Weight: Optimized for portability."
    ],
    lifespan: "10+ Years (Solar Cells)",
    warranty: "1-2 Year Limited Warranty",
    types: [
      { name: "Foldable Suitcase Kits", description: "Rigid panels that fold like a briefcase. Extremely durable." },
      { name: "Flexible Solar Mats", description: "Ultra-thin mats that roll up. Perfect for hiking and light travel." },
      { name: "Integrated Power Stations", description: "Battery and panels in one portable unit for emergency backup." }
    ]
  }
};
